#!/usr/bin/python3
import traceback

try:
    # your code goes here
except Exception as e:
    traceback.print_exc()
